using Unity.VisualScripting;
using UnityEngine;

public class SceneTrigger : MonoBehaviour
{
    [Header("Param√®tres de la Sc√®ne Cible")]
    [Tooltip("Le nom exact de la sc√®ne √† charger. Doit √™tre ajout√© aux Build Settings !")]
    public string nomDeSceneCible;

    [Tooltip("L'ID ou le Tag que votre vaisseau de joueur doit avoir (ex: 'PlayerShip').")]
    public string tagDuVaisseauJoueur = "Player";

    public SceneLoader sceneLoader;
    public GameObject loading_panel;

    [Header("Param√®tres d'√âcoute")]
    [Tooltip("L'ID unique que ce loader √©coute (ex: 'MarsEntrance').")]
    public string idCibleAEcouter;

    void Start()
    {
        // üö® S'abonner √† l'√©v√©nement du Manager
        if (GPSManager.Instance != null)
        {
            GPSManager.Instance.OnTargetReached += OnCibleAtteinte;
        }
    }

    void OnDestroy()
    {
        // Se d√©sabonner
        if (GPSManager.Instance != null)
        {
            GPSManager.Instance.OnTargetReached -= OnCibleAtteinte;
        }
    }
    
    /// <summary>
    /// M√©thode appel√©e lorsque la cible est atteinte via l'√©v√©nement du GPSManager.
    /// </summary>
    /// <param name="reachedId">L'ID de la cible qui vient d'√™tre atteinte.</param>
    private void OnCibleAtteinte(string reachedId)
    {
        // 1. Comparer l'ID re√ßu avec l'ID que ce script √©coute
        if (reachedId == idCibleAEcouter)
        {
            // 2. L'ID correspond ! Charger la sc√®ne.
            if (!string.IsNullOrEmpty(nomDeSceneCible))
            {
                if ( QuestManager.Instance != null && QuestManager.Instance.activeQuests.Count > 0)
                {
                    QuestManager.Instance.NotifyPlanetVisited(reachedId);
                }
                Debug.Log($"[SceneLoaderListener: {idCibleAEcouter}] La cible correspond. Chargement de la sc√®ne : {nomDeSceneCible}");
                loading_panel.SetActive(true);
                sceneLoader.LoadScene(nomDeSceneCible);
            }
            else
            {
                Debug.LogError($"[SceneLoaderListener: {idCibleAEcouter}] Sc√®ne cible non d√©finie !");
            }
        }
    }
}
